config/routes.rb
Blog::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  resources :post_cats

  resources :posts
  
  get "about/index"

  resources :users
    resources :user_sessions

  	match 'login' => "user_sessions#new", :as => :login
  	match 'logout' => "user_sessions#destroy", :as => :logout

  	match 'new_contact' =>  'contact_us#new', :conditions => { :method => :get }
  	resources :contact_us, :only => [:new, :create]
  	match 'contact_us' => 'contact_us#new'
  

  root :to => 'dash#index'

end

app/models/post_cat.rb
class PostCat < ActiveRecord::Base
  has_many :posts
  attr_accessible :cat_name, :catpic_content_type, :catpic_file_name, :catpic_file_size, :description, :featured
  validates_presence_of :cat_name
end

app/controllers/post_cats_controller.rb
class PostCatsController < ApplicationController
  skip_filter :require_user
  before_filter :require_user, :except => [:show]
  # GET /post_cats
  # GET /post_cats.json
  def index
    @post_cats = PostCat.all
    @page_title = "Post Categories"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @post_cats }
    end
  end

  # GET /post_cats/1
  # GET /post_cats/1.json
  def show
    @post_cat = PostCat.find(params[:id])
    @posts = @post_cat.posts
    @page_title = "Recent Posts"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @post_cat }
    end
  end

  # GET /post_cats/new
  # GET /post_cats/new.json
  def new
    @post_cat = PostCat.new
    @page_title = "New Post Category"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @post_cat }
    end
  end

  # GET /post_cats/1/edit
  def edit
    @post_cat = PostCat.find(params[:id])
    @page_title = "Edit Post Category"
  end

  # POST /post_cats
  # POST /post_cats.json
  def create
    @post_cat = PostCat.new(params[:post_cat])

    respond_to do |format|
      if @post_cat.save
        format.html { redirect_to @post_cat, :notice => 'Post cat was successfully created.' }
        format.json { render :json => @post_cat, :status => :created, :location => @post_cat }
      else
        format.html { render :action => "new" }
        format.json { render :json => @post_cat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /post_cats/1
  # PUT /post_cats/1.json
  def update
    @post_cat = PostCat.find(params[:id])
    @page_title = "Update Post Category"

    respond_to do |format|
      if @post_cat.update_attributes(params[:post_cat])
        format.html { redirect_to @post_cat, :notice => 'Post cat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post_cat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /post_cats/1
  # DELETE /post_cats/1.json
  def destroy
    @post_cat = PostCat.find(params[:id])
    @post_cat.destroy

    respond_to do |format|
      format.html { redirect_to post_cats_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/post_cats_helper.rb
module PostCatsHelper
end

app/views/post_cats/_form.html.erb
<div id="postListing">
	<%= form_for(@post_cat) do |f| %>
	  <% if @post_cat.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@post_cat.errors.count, "error") %> prohibited this post_cat from being saved:</h2>

	      <ul>
	      <% @post_cat.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	  <div class="field">
	    <%= f.label :cat_name %><br />
	    <%= f.text_field :cat_name %>
	  </div>
	  <div class="field">
	    <%= f.label :description %><br />
	    <%= f.text_area :description %>
	  </div>
	  <div class="actions">
	    <%= f.submit %>
	  </div>
	<% end %>
</div>

app/views/post_cats/edit.html.erb
<div id="postListing">
	<h1>Editing post_cat</h1>
		<%= render 'form' %>
		<%= link_to 'Show', @post_cat %> |
		<%= link_to 'Back', post_cats_path %>
</div>

app/views/post_cats/index.html.erb
<div id="postListing">
	<h1>Listing post_cats</h1>
		<table>
	  		<tr>
	    		<th>Cat name</th>
	  		</tr>
				<% @post_cats.each do |post_cat| %>
	  		<tr>
	    		<td><%= post_cat.cat_name %></td>
	    		<td><%= link_to 'Show', post_cat %></td>
	    		<td><%= link_to 'Edit', edit_post_cat_path(post_cat) %></td>
	    		<td><%= link_to 'Destroy', post_cat, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
	  		</tr>
				<% end %>
			</table><br />
	<%= link_to 'New Post cat', new_post_cat_path %>
</div>

app/views/post_cats/new.html.erb
<div id="postListing">
<h1>New post_cat</h1>
	<%= render 'form' %>
	<%= link_to 'Back', post_cats_path %>
</div>

app/views/post_cats/show.html.erb
<div id="postListing">
	<h1>Recent <%= @post_cat.cat_name %> Posts</h1>
	<% if @posts.present? %>
		<% @posts.each do |post| %>
			<i><%= link_to post.name, post %></i><br />
				<div class="text"><%= post.blurb %></div><br /><br />
					<%= render :partial => "/posts/item_list", :locals => {:post => post} %>
				<div class="text"><%== post.description %></div>
					<p><%= image_tag('/assets/postdivider.png') %></p>
		<% end %>
	<% end %>
</div>